name: websitegyd
description: A new Flutter project.

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.0
  hexcolor: ^1.0.6
  google_fonts: ^1.1.1
  carousel_slider: ^2.3.1
  dynamic_theme: ^1.0.1
  provider: ^4.3.2+2
  get: ^3.15.0
  flutter_web_scrollbar: ^0.0.3
  # shared_preferences: ^0.5.12+4
  # firebase_auth: ^0.18.2
  # firebase_core: ^0.5.1
  # firebase_storage: ^5.0.0
  # cloud_firestore: ^0.14.2
  # google_sign_in: ^4.5.5
  flag: ^3.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^1.6.2
  build_web_compilers: ^2.0.0


flutter:
  uses-material-design: true

  fonts:
    - family: Montserrat
      fonts:
        - asset: fonts/Montserrat-Regular.ttf

    - family: Electrolize
      fonts:
        - asset: fonts/Electrolize-Regular.ttf

  assets:
    - assets/images/
    - assets/images/flags/